services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
